[workspace]
members = ["packages/*", "contracts/*"]

[workspace.package]
version       = "0.18.0"
edition       = "2021"
license       = "MIT"
repository    = "https://github.com/dojo-trading/cw404"
homepage      = "https://dojo.trading"
documentation = "https://docs.dojo.trading"
rust-version  = "1.65"

[workspace.dependencies]
cosmwasm-schema = "^1.2"
cosmwasm-std    = "^1.2"
cw2             = "^1.1"
cw20            = "^1.1"
cw721           = { version = "*", path = "./packages/cw721" }
cw721-base      = { version = "*", path = "./contracts/cw721-base" }
cw721-base-016  = { version = "0.16.0", package = "cw721-base" }
cw-multi-test   = "^0.20"
cw-ownable      = "^0.5"
cw-storage-plus = "^1.1"
cw-utils        = "^1.0"
schemars        = "^0.8"
serde           = { version = "1.0.152", default-features = false, features = ["derive"] }
thiserror       = "^1.0"

[profile.release.package.cw721-base]
codegen-units = 1
incremental   = false

[profile.release.package.cw721-metadata-onchain]
codegen-units = 1
incremental   = false

[profile.release.package.cw721-fixed-price]
codegen-units = 1
incremental   = false

[profile.release.package.cw721-non-transferable]
codegen-units = 1
incremental   = false

[profile.release.package.cw721-receiver]
codegen-units = 1
incremental   = false

[profile.release]
rpath            = false
lto              = true
overflow-checks  = true
opt-level        = 3
debug            = false
debug-assertions = false
